version: "3.9"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    network_mode: host
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - '/:/host:ro'
